### ISSUE TITLE
Implement CI/CD cycle

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-gov-uk-prod#1]
Implement CI/CD to:
Automate deployment to AWS.
Automatic daily fully destroy and deploy of the test site

The code to deploy is here:
https://github.com/filetrust/k8-reverse-proxy/tree/master/Release01

**Comment by Rajwinder1985** [comment]
we can use terraform for the aws resource deployment and destroy and for CI-CD we can integrate Jenkins

**Comment by MariuszFerdyn** [comment]
Should not we use AWS native tools?
Or Github Actions?

**Comment by Rajwinder1985** [comment]
I recommend Jenkins for the CI-CD part as it provides easy integration for the automation

**Comment by Rajwinder1985** [comment]
> Should not we use AWS native tools?
> Or Github Actions?

My approach:-
Code on Github/Gitlab > prepare docker setup for the project deployment on server > Deploy project on server > Automate deployment in Jenkins
>> I need an AWS IAM user access or a server [linux] access with a sufficient amount of resources (RAM & CPU core).

**Comment by mahnouman** [comment]
So, just a status about who is doing what:
@pranaysahith CI/CD using Github Actions
@MariuszFerdyn  CI/CD using AWS CodePipeline

**Comment by mahnouman** [comment]
So, just a status about who is doing what:
@pranaysahith CI/CD using Github Actions
@MariuszFerdyn  CI/CD using AWS CodePipeline
@Rajwinder1985 CI/CD using Jenkins

**Comment by mahnouman** [comment]
@pranaysahith 
Please check if Github Actions has the capability to create / tear down EC2 instances themselves and also considering reusing same public IP of the teared down VM, just checking if such capability exist within Github Actions.

**Comment by MariuszFerdyn** [comment]
PR created - implemented CodePipeline and CloudFormation - I think that CloudFormation is better... but it depends...
