### ISSUE TITLE
Test Building a docker

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-gov-uk-prod#2]
Test building a docker using the information in this:
https://github.com/filetrust/k8-reverse-proxy/tree/master/Release01

**Comment by naderaly** [comment]
Tested & passed
![Docker-up](https://user-images.githubusercontent.com/58347752/93201248-39a8d900-f751-11ea-9e22-c0f6b7ac44a1.png)

**Comment by mahnouman** [comment]
> Tested & passed
> ![Docker-up](https://user-images.githubusercontent.com/58347752/93201248-39a8d900-f751-11ea-9e22-c0f6b7ac44a1.png)

Hello @naderaly Can you please verify that the website which is being (Reverse Proxied) is up, so we proceed closing this issue, thanks
