### ISSUE TITLE
Re-Deploy gov.uk

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/s-gov-uk-prod#8]
Redeploy gov.uk while using local ICAP instance.
Optionally consider using the pipelines.

**Comment by NourEddineX** [comment]
ICAP service deployed : https://www.gov.uk.glasswall-icap.com

**Comment by mahnouman** [comment]
@NourEddineX 
Thanks for bringing the site back, but I get this issue:

**Comment by NourEddineX** [comment]
@mahnouman  thanks for reporting it, I've fixed that
